import './styles/reset.css';
import './styles/tokens.css';
import './styles/base.css';
import './styles/components.css';
import './styles/sections.css';
import './styles/motion.css';
import './styles/responsive.css';
import './styles/editorial.css';
import { initNavigation } from './modules/navigation.js';
import { initProjectFilter } from './modules/project-filter.js';
import { initRevealMotion } from './modules/reveal-motion.js';
import { prefersReducedMotion } from './modules/reduced-motion.js';
import { initPortfolioAssistant } from './modules/portfolio-assistant.js';
import { initContactForm } from './modules/contact-form.js';
import { initProjectModal } from './modules/project-modal.js';
import { initMetricCounters } from './modules/metric-counters.js';

document.documentElement.classList.add('js');
document.querySelector('[data-current-year]').textContent = String(new Date().getFullYear());
document.querySelectorAll('img').forEach((image) => image.addEventListener('error', () => image.closest('.media-frame, .hero-visual, .profile-frame')?.classList.add('has-media-error')));
initNavigation();
initProjectFilter();
initPortfolioAssistant();
initContactForm();
initProjectModal();
initMetricCounters();
if (!prefersReducedMotion()) initRevealMotion();
